package BasicsJava;

import java.util.Scanner;

public class IntroToJava {

    public static void main(String[] args) {
        try (Scanner sc = new Scanner(System.in)) {
            boolean running = true;

            System.out.println("Welcome to Java tutorial.");
            System.out.println("This program provides in-depth knowledge on Java basics.\n");

            while (running) {
                printMenu();
                int choice = readChoice(sc);

                switch (choice) {
                    case 1:
                        explainJava();
                        break;
                    case 2:
                        explainPlatformIndependence();
                        break;
                    case 3:
                        explainBytecode();
                        break;
                    case 4:
                        explainCompiledAndInterpreted();
                        break;
                    case 5:
                        explainEntryPoint();
                        break;
                    case 6:
                        explainMainMethod();
                        break;
                    case 7:
                        explainJVM();
                        break;
                    case 8:
                        explainJIT();
                        break;
                    case 9:
                        explainJVMMemory();
                        break;
                    case 10:
                        explainJVMJDKJRE();
                        break;
                    case 11:
                        explainStepsOfJVM();
                        break;
                    case 12:
                        System.out.println("Exiting...");
                        running = false;
                        break;
                    default:
                        System.out.println("Invalid choice. Please enter a number from 1 to 10.");
                }

                System.out.println();
            }
        }
    }

    private static void printMenu() {
        System.out.println("Choose a question:");
        System.out.println("1. Say a few words about Java");
        System.out.println("2. Is Java platform independent? Why?");
        System.out.println("3. What is Bytecode?");
        System.out.println("4. Why is Java both compiled and interpreted?");
        System.out.println("5. What is the entry point of a Java program?");
        System.out.println("6. Why is main() declared as public, static and void?");
        System.out.println("7. What is a JVM?");
        System.out.println("8. What is JIT?");
        System.out.println("9. What are the memory storages available in JVM?");
        System.out.println("10. Explain JVM, JDK, JRE");
        System.out.println("11. Explain the execution process of JVM");
        System.out.println("12. Exit!");
        System.out.print("Enter your choice: ");
    }

    private static int readChoice(Scanner sc) {
        while (!sc.hasNextInt()) {
            System.out.println("Invalid input. Please enter a number.");
            sc.next();
            System.out.print("Enter your choice: ");
        }
        return sc.nextInt();
    }

    private static void explainJava() {
        String message = """
                Java is a high-level, class-based, object-oriented programming language developed by James Gosling.
                It follows the principle of Write Once, Run Anywhere (WORA), which is achieved through the JVM.

                Java is strongly typed, meaning variables must be declared with a data type before use.
                It is known for simplicity, object-oriented design, portability, security, robustness,
                multithreading, and good runtime performance.
                """;
        System.out.println(message);
    }

    private static void explainPlatformIndependence() {
        String message = """
                Java is platform independent because Java source code is compiled into bytecode (.class file),
                and that bytecode can run on any system that has a compatible JVM.

                The JVM itself is platform dependent, but it provides a common runtime environment.
                Because of that, the same bytecode can run on different operating systems.

                Interview version:
                Java is platform independent because its bytecode runs on any platform with a JVM.
                """;
        System.out.println(message);
    }

    private static void explainBytecode() {
        String message = """
                Bytecode is the intermediate, platform-independent code generated by the Java compiler (javac)
                from Java source code.

                It is stored in .class files and executed by the JVM.
                Bytecode is one of the main reasons Java supports platform independence.
                """;
        System.out.println(message);
    }

    private static void explainCompiledAndInterpreted() {
        String message = """
                Java is both compiled and interpreted.

                First, the Java compiler (javac) compiles source code into bytecode.
                Then, the JVM interprets or executes that bytecode at runtime.

                For better performance, the JVM also uses JIT compilation to convert frequently used bytecode
                into native machine code.
                """;
        System.out.println(message);
    }

    private static void explainEntryPoint() {
        String message = """
                The entry point of a Java application is:

                public static void main(String[] args)

                When you run a Java program, the JVM looks for this method and starts execution from it.
                Without a proper main method, the program cannot start normally.
                """;
        System.out.println(message);
    }

    private static void explainMainMethod() {
        String message = """
                The main method is declared as public, static, and void for specific reasons:

                public:
                The JVM must be able to access it from outside the class.

                static:
                The JVM calls main() without creating an object of the class.

                void:
                The JVM does not expect any return value from the main method.

                String[] args:
                It allows command-line arguments to be passed to the program.
                """;
        System.out.println(message);
    }

    private static void explainJVM() {
        String message = """
                JVM stands for Java Virtual Machine.

                It is the runtime environment that loads, verifies, and executes Java bytecode.
                It also handles memory management, garbage collection, and runtime execution.

                The JVM is platform dependent, but it makes Java applications platform independent by allowing
                the same bytecode to run on different systems.
                """;
        System.out.println(message);
    }

    private static void explainJIT() {
        String message = """
                JIT stands for Just-In-Time compiler.

                It is a part of the JVM that improves performance by identifying frequently executed code
                (hot code) and compiling it into native machine code.

                This avoids interpreting the same bytecode repeatedly and makes Java programs faster at runtime.
                """;
        System.out.println(message);
    }

    private static void explainJVMMemory() {
        String message = """
                JVM memory is divided into several runtime areas:

                1. Method Area
                   Stores class metadata, static variables, and runtime constant pool.

                2. Heap
                   Stores objects and instance data.

                3. Stack
                   Stores method calls, local variables, and references.
                   Each thread has its own stack.

                4. Program Counter Register
                   Stores the address of the current instruction being executed.

                5. Native Method Stack
                   Supports execution of native methods.

                Memory shortcut:
                Stack -> local variables
                Heap -> objects / instance data
                Method Area -> class-level data / static variables
                """;
        System.out.println(message);

    }

    private static void explainJVMJDKJRE(){
        String message = """
                JDK : Java Development Kit provides a complete development environment to write, compile, debug
                and run java programs. Includes JRE + development tools like javac, jdb etc
                
                JRE : Java Runtime Environment provides the runtime environment required to execute Java application
                Includes JVM + core libraries
                
                JVM : Java Virtual Machine is the runtime environment that loads, verifies, and executes Java bytecode.
                It also handles memory management, garbage collection, and runtime execution
                """;
        System.out.println(message);
    }

    private static void explainStepsOfJVM(){
        String message = """
                Java flow is:
                .java file → javac → .class file (bytecode) → JVM → machine code execution
                
                So the JVM does not run .java source code directly. It runs the compiled .class bytecode.
                But JVM does not blindly execute the file. It goes through a sequence of steps.
                
                Those steps are:
                
                Class Loading
                Linking
                Initialization
                Execution
                Memory management / Garbage collection
                
                Step 1: Loading
                
                The JVM first loads the required .class files into memory.
                This is done by the Class Loader Subsystem.
                
                What happens here?
                JVM looks for the main class you want to run
                It loads that class file into memory
                It may also load other classes used by your program
                
                Types of class loaders
                Bootstrap ClassLoader → loads core Java classes like java.lang.*
                Platform/Extension ClassLoader → loads platform libraries
                Application ClassLoader → loads classes from your project/classpath
                
                If your code uses:
                
                System.out.println("Hello");
                
                then JVM must load:
                
                your class
                System
                PrintStream
                other needed Java classes
                
                Step 2: Linking
                
                After loading, JVM links the class. Linking has 3 parts:
                
                a) Verification
                
                The JVM checks whether the bytecode is valid and safe.
                
                It checks things like:
                
                is the bytecode format correct?
                is there illegal memory access?
                does it break Java rules?
                
                This is a major reason Java is considered safer than languages that directly run native code.
                
                b) Preparation
                
                Memory is allocated for:
                
                static variables
                class-level structures
                
                At this stage, default values are assigned.
                
                Example:
                
                static int x;
                
                During preparation, memory is reserved and x gets default value 0.
                
                c) Resolution
                
                Symbolic references are converted into actual direct references.

                Step 3: Initialization
                
                Now the class is initialized.
                
                This means:
                
                static variables get their actual assigned values
                static blocks run
                
                Example:
                
                class Demo {
                    static int x = 10;
                
                    static {
                        System.out.println("Static block runs");
                    }
                }
                
                When JVM initializes this class:
                
                x becomes 10
                static block executes
                Important
                
                Preparation gives default values.
                Initialization gives actual programmer-defined values.
                
                Step 4: Execution
                
                Now JVM starts executing the program.
                
                It looks for:
                
                public static void main(String[] args)
                
                and starts from there.
                
                What happens during execution?
                Each method call creates a stack frame
                Local variables go into the stack
                Objects are created in the heap
                Bytecode is interpreted or optimized by JIT
                Step 5: Interpretation and JIT Compilation
                
                JVM has an execution engine.
                
                This engine runs the bytecode.
                
                Two ways it works:
                a) Interpreter
                
                Reads bytecode instruction by instruction and executes it.
                
                This is simple, but slower if the same code runs many times.
                
                b) JIT Compiler
                
                When JVM notices some code is running very frequently, it marks it as hot code and compiles it into native machine code.
                
                Then next time, it runs faster.
                
                Important distinction
                JVM = whole runtime system
                JIT = performance optimization component inside JVM
                
                Step 6: Runtime Memory Areas Used During Execution
                
                While the program runs, JVM uses memory areas.
                
                Step 7: Garbage Collection
                
                When objects in heap are no longer referenced, JVM can remove them automatically using Garbage Collection.
                
                This helps manage memory automatically.
                
                Example:
                
                Student s = new Student();
                s = null;
                
                If no references remain, that object becomes eligible for garbage collection.
                
                Important
                
                GC does not immediately delete objects the moment they become unused.
                It runs when JVM decides it is needed.
                
                Java source code is compiled into bytecode by javac. When we run the program, JVM loads the
                required classes, verifies and links them, initializes static data, and then executes bytecode
                through the execution engine using interpretation and JIT compilation, while managing memory and
                garbage collection.
                """;
        System.out.println(message);
    }
}